### ISSUE TITLE
License: GPL or LGPL?

### ISSUE THREAD

**Issue by rekado** [lloda/guile-ffi-fftw#1]
The LICENSE file is that of the LGPL yet the copyright header of the source file says GPLv3+.  Which license actually applies?

**Comment by lloda** [comment]
Thanks for pointing this out @rekado . My original intention was to use the LGPL. I've fixed the mismatches in the source.

**Comment by lloda** [comment]
I had the same error in another project... :-/

**Comment by lloda** [comment]
Should be ok now. Thx again for the report @rekado !
